# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  lint-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run ci
        env:
          REPORTER: 'min'

  coveralls:
    needs: lint-coverage
    runs-on: ubuntu-latest

    name: Send coverage to Coveralls
    steps:
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: lint-coverage
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node_version:
          - 10
          - 12
          - 16

    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node_version }} - ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
        env:
          REPORTER: 'min'